name: Build Test And Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Clone the repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Replace the configuration file
      run: echo "export const settings = {host: \"http://localhost:3030/\"};" > src/config.js
    - name: Start backend
      run: npm run server &
    - name: Start Frontend
      run: npm run start &
    - name: Install browsers
      run: npx playwright install
    - name: Start tests
      run: npm run test
